### ISSUE TITLE
Faster bitmap

### ISSUE THREAD

**Issue by sverhoeven** [3D-e-Chem/kripodb#52]
Switch to http://roaringbitmap.org/ it has `len(a & b)` as single method, which is faster.

**Comment by sverhoeven** [comment]
Also on clean conda3 install it produces an error
```python
    find_module called for: intbitset [assertion]
    find_module called for: intbitset_helper [assertion]
Traceback (most recent call last):
  File "/tmp/hh/kripo/conda/lib/python3.6/site-packages/_pytest/config.py", line 334, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/tmp/hh/kripo/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/hh/kripo/conda/lib/python3.6/site-packages/_pytest/config.py", line 365, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/tmp/hh/kripo/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/hh/kripo/conda/lib/python3.6/site-packages/_pytest/config.py", line 371, in _importconftest
    mod = conftestpath.pyimport()
  File "/tmp/hh/kripo/conda/lib/python3.6/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/tmp/hh/kripo/conda/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/tmp/hh/kripo/tests/conftest.py", line 4, in <module>
    from kripo.ligandexpodb import LigandExpoDb
  File "/tmp/hh/kripo/kripo/ligandexpodb.py", line 1, in <module>
    from kripodb.db import SqliteDb, SqliteDict
  File "/tmp/hh/kripo/conda/lib/python3.6/site-packages/kripodb/db.py", line 26, in <module>
    from intbitset import intbitset
  File "intbitset.pyx", line 52, in init intbitset (intbitset/intbitset.c:14153)
ImportError: cannot import name __version__
ERROR: could not load /tmp/hh/kripo/tests/conftest.py
```
when `PYTEST_DEBUG=1 pytest` is run.
